In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.datasets import fetch_openml

def load_boston_dataset():
    dataset = fetch_openml(name='boston', version=1)
    return dataset.data, dataset.target

X, y = load_boston_dataset()

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:1022: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [4]:
# In this example we will use the boston housing dataset, no pandas conversion
#from sklearn.datasets import load_boston

#boston = load_boston()
# X = boston.data
# y = boston.target
# print(boston.DESCR)

In [6]:
X

CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  \
0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0   
1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0   
2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0   
3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0   
4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0   
..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...   
501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0   
502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0   
503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0   
504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0   
505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [8]:
X['CHAS'] = X['CHAS'].astype(float)
X['RAD'] = X['RAD'].astype(float)

In [9]:
print(X.shape)
X.head()

(506, 13)


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [10]:
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: MEDV, dtype: float64

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state = 1)

In [29]:
print(X_train.shape)
X_train.head()

(379, 13)


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
172  0.13914   0.0   4.05   0.0  0.510  5.572  88.5  2.5961  5.0  296.0   
80   0.04113  25.0   4.86   0.0  0.426  6.727  33.5  5.4007  4.0  281.0   
46   0.18836   0.0   6.91   0.0  0.448  5.786  33.3  5.1004  3.0  233.0   
318  0.40202   0.0   9.90   0.0  0.544  6.382  67.2  3.5325  4.0  304.0   

     PTRATIO       B  LSTAT  
502     21.0  396.90   9.08  
172     16.6  396.90  14.69  
80      19.0  396.90   5.29  
46      17.9  396.90  14.15  
318     18.4  395.21  10.36

In [13]:
print(X_test.shape)
X_test.head()

(127, 13)


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
307  0.04932  33.0   2.18   0.0  0.472  6.849  70.3  3.1827   7.0  222.0   
343  0.02543  55.0   3.78   0.0  0.484  6.696  56.4  5.7321   5.0  370.0   
47   0.22927   0.0   6.91   0.0  0.448  6.030  85.5  5.6894   3.0  233.0   
67   0.05789  12.5   6.07   0.0  0.409  5.878  21.4  6.4980   4.0  345.0   
362  3.67822   0.0  18.10   0.0  0.770  5.362  96.2  2.1036  24.0  666.0   

     PTRATIO       B  LSTAT  
307     18.4  396.90   7.53  
343     17.6  396.90   7.18  
47      17.9  392.74  18.80  
67      18.9  396.21   8.10  
362     20.2  380.79  10.19

## Linear Regression (& Variants)

In [14]:
# Create linear regression
regr = LinearRegression()

# Train the linear regression
model = regr.fit(X_train, y_train)

# Score the model
model.score(X_test, y_test)

0.7789410172622854

In [17]:
model.predict(X_test)

array([32.37816533, 27.95684437, 18.07213891, 21.63166556, 18.93029508,
       19.96277202, 32.2834674 , 18.06715668, 24.72989076, 26.85359369,
       27.23326816, 28.57021239, 21.18778302, 26.94393815, 23.37892579,
       20.89176865, 17.11746934, 37.73997945, 30.51980066,  8.44489436,
       20.86557977, 16.21989418, 25.13605925, 24.77658813, 31.40497629,
       11.02741407, 13.82097563, 16.80208261, 35.94637198, 14.7155729 ,
       21.23939821, 14.15079469, 42.72492585, 17.83887162, 21.84610225,
       20.40178099, 17.50287927, 27.00093206,  9.80760408, 20.00288662,
       24.27066782, 21.06719021, 29.47089776, 16.48482565, 19.38852695,
       14.54778282, 39.39838319, 18.09810655, 26.22164983, 20.60676525,
       25.09994066, 24.48366723, 25.02297948, 26.84986898,  5.01517985,
       24.12809513, 10.72843392, 26.83178157, 16.8023533 , 35.48142073,
       19.50937911, 27.43260347, 16.58016763, 19.151488  , 10.9990262 ,
       32.05016535, 36.32672849, 21.8596379 , 24.8158357 , 25.32

In [18]:
np.array(y_test)

array([28.2, 23.9, 16.6, 22. , 20.8, 23. , 27.9, 14.5, 21.5, 22.6, 23.7,
       31.2, 19.3, 19.4, 19.4, 27.9, 13.9, 50. , 24.1, 14.6, 16.2, 15.6,
       23.8, 25. , 23.5,  8.3, 13.5, 17.5, 43.1, 11.5, 24.1, 18.5, 50. ,
       12.6, 19.8, 24.5, 14.9, 36.2, 11.9, 19.1, 22.6, 20.7, 30.1, 13.3,
       14.6,  8.4, 50. , 12.7, 25. , 18.6, 29.8, 22.2, 28.7, 23.8,  8.1,
       22.2,  6.3, 22.1, 17.5, 48.3, 16.7, 26.6,  8.5, 14.5, 23.7, 37.2,
       41.7, 16.5, 21.7, 22.7, 23. , 10.5, 21.9, 21. , 20.4, 21.8, 50. ,
       22. , 23.3, 37.3, 18. , 19.2, 34.9, 13.4, 22.9, 22.5, 13. , 24.6,
       18.3, 18.1, 23.9, 50. , 13.6, 22.9, 10.9, 18.9, 22.4, 22.9, 44.8,
       21.7, 10.2, 15.4, 25.3, 23.3,  7.2, 21.2, 11.7, 27. , 29.6, 26.5,
       43.5, 23.6, 11. , 33.4, 36. , 36.4, 19. , 20.2, 34.9, 50. , 19.3,
       14.9, 26.6, 19.9, 24.8, 21.2, 23.9])

In [19]:
np.sqrt(((model.predict(X_test)-np.array(y_test))**2).sum()/len(X_test))

4.679504823808768

In [ ]:
model.coef_

array([-1.14428903e-01,  5.71299780e-02,  3.83002824e-02,  2.42854641e+00,
       -2.12326236e+01,  2.87723416e+00,  6.91118094e-03, -1.47158266e+00,
        3.05784197e-01, -1.06750361e-02, -9.96138270e-01,  6.27746234e-03,
       -5.57414427e-01])

In [30]:
#ridge tries to control the coefficients -
#may pay a bit in score (at least if we measure mean squared error of training data) but reduces variance of coefficients, which should provide less extreme preditions
#and that may actually improve generalization capability, since we're less likely to produce large errors due to huge coefficients
#a good example where a better theoretical score from the "mathematical" justification is not necessarily the better method when we consider the practical "score is everything" approach of ML
from sklearn.linear_model import Ridge

# Create linear regression
regr = Ridge(alpha=1.0)

# Train the linear regression
model = regr.fit(X_train, y_train)

# Score the model
model.score(X_test, y_test)

0.784777431688241

In [31]:
# in this case we have improvement but it is... moderate
model.coef_

array([-1.09313326e-01,  5.81466109e-02, -6.57912472e-03,  2.17625586e+00,
       -1.14648161e+01,  2.96948364e+00, -1.23491124e-03, -1.33558053e+00,
        2.86708621e-01, -1.17634405e-02, -8.80356116e-01,  6.85811788e-03,
       -5.68412252e-01])

In [32]:
#we can exaggerate the effect

from sklearn.linear_model import Ridge

# Create linear regression
regr = Ridge(alpha=10000)
# Train the linear regression
model = regr.fit(X_train, y_train)
model.coef_

array([-0.07699966,  0.05802523, -0.04732444,  0.01219631, -0.00076672,
        0.0703664 ,  0.00581543, -0.08075508,  0.09267065, -0.01020258,
       -0.13586625,  0.00792909, -0.43855133])

In [34]:
from sklearn.linear_model import Lasso

# Create linear regression
regr = Lasso(alpha=1.0)

# Train the linear regression
model = regr.fit(X_train, y_train)

# Score the model
model.score(X_test, y_test)

0.662198077052326

In [35]:
#not worth it in this case, since it is underfitting, but see what happens to the coefficients -> it may be very helpful to reduce the dimensionality of our problem.
model.coef_

array([-0.06878405,  0.05536254, -0.        ,  0.        , -0.        ,
        0.        ,  0.02336436, -0.54610017,  0.24646698, -0.01288932,
       -0.73552217,  0.00590525, -0.79338245])

## Decision Tree Regression

In [39]:
# Import libraries
from sklearn.tree import DecisionTreeRegressor

In [47]:
# Create decision tree classifer object
regr = DecisionTreeRegressor()

# Train regression tree model
model = regr.fit(X_train, y_train)

# Score the model
model.score(X_test, y_test)

0.8463533764100426

In [ ]:
# NTS: depending on room energy, explain random nature of split selection

In [48]:
y_pred = regr.predict(X_test)

In [49]:
y_pred

array([36.1, 27.5, 21.7, 18.9, 21.7, 21.4, 30.8, 21.7, 17.8, 23.9, 32. ,
       34.9, 17.1, 17.1, 20.3, 15. , 13.1, 37.6, 22.9, 15.4, 17.1, 13.1,
       22. , 23.8, 24.2,  8.7, 13.2, 18.2, 48.8, 12.5, 30.5, 23.1, 50. ,
       17.8, 26.4, 21.8, 17.8, 33.4, 13.8, 19.9, 24.1, 22.2, 25.1, 17.3,
       13.8,  8.4, 50. , 10.4, 19.1, 16.1, 23. , 22. , 22.9, 24.4,  7. ,
       23.1, 11.3, 22.2, 21.7, 37.6, 13.1, 28.4, 12.5, 13.1, 19.1, 36.1,
       37.6, 22.9, 23.2, 17.4, 25. ,  5.6, 16.8, 21.7, 21.7, 21.2, 50. ,
       24.7, 21.6, 28.5, 16.2, 20.3, 37. , 10.8, 24.6, 23.2, 17.1, 24.8,
       21.8, 17.8, 25. , 48.8, 15.2, 20.7, 16.1, 20.7, 22. , 21.4, 37.6,
       23.2, 19.1, 18.4, 24.1, 24.7,  8.8, 22.2, 19.1, 21.6, 26.4, 27.5,
       50. , 24.6, 13.4, 36.1, 36.5, 37. , 21.2, 18.2, 28.7, 48.8, 17.4,
       13.4, 28.4, 21.7, 31.5, 21.8, 23.4])

In [51]:
np.array(y_test)

array([28.2, 23.9, 16.6, 22. , 20.8, 23. , 27.9, 14.5, 21.5, 22.6, 23.7,
       31.2, 19.3, 19.4, 19.4, 27.9, 13.9, 50. , 24.1, 14.6, 16.2, 15.6,
       23.8, 25. , 23.5,  8.3, 13.5, 17.5, 43.1, 11.5, 24.1, 18.5, 50. ,
       12.6, 19.8, 24.5, 14.9, 36.2, 11.9, 19.1, 22.6, 20.7, 30.1, 13.3,
       14.6,  8.4, 50. , 12.7, 25. , 18.6, 29.8, 22.2, 28.7, 23.8,  8.1,
       22.2,  6.3, 22.1, 17.5, 48.3, 16.7, 26.6,  8.5, 14.5, 23.7, 37.2,
       41.7, 16.5, 21.7, 22.7, 23. , 10.5, 21.9, 21. , 20.4, 21.8, 50. ,
       22. , 23.3, 37.3, 18. , 19.2, 34.9, 13.4, 22.9, 22.5, 13. , 24.6,
       18.3, 18.1, 23.9, 50. , 13.6, 22.9, 10.9, 18.9, 22.4, 22.9, 44.8,
       21.7, 10.2, 15.4, 25.3, 23.3,  7.2, 21.2, 11.7, 27. , 29.6, 26.5,
       43.5, 23.6, 11. , 33.4, 36. , 36.4, 19. , 20.2, 34.9, 50. , 19.3,
       14.9, 26.6, 19.9, 24.8, 21.2, 23.9])

In [52]:
X_train.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
172  0.13914   0.0   4.05   0.0  0.510  5.572  88.5  2.5961  5.0  296.0   
80   0.04113  25.0   4.86   0.0  0.426  6.727  33.5  5.4007  4.0  281.0   
46   0.18836   0.0   6.91   0.0  0.448  5.786  33.3  5.1004  3.0  233.0   
318  0.40202   0.0   9.90   0.0  0.544  6.382  67.2  3.5325  4.0  304.0   

     PTRATIO       B  LSTAT  
502     21.0  396.90   9.08  
172     16.6  396.90  14.69  
80      19.0  396.90   5.29  
46      17.9  396.90  14.15  
318     18.4  395.21  10.36

In [53]:
#let's look at the decision tree
from sklearn.tree import export_text

r = export_text(regr, feature_names=list(X_train.columns))
print(r)

|--- LSTAT <= 9.76
|   |--- RM <= 7.43
|   |   |--- DIS <= 1.48
|   |   |   |--- value: [50.00]
|   |   |--- DIS >  1.48
|   |   |   |--- RM <= 6.54
|   |   |   |   |--- RM <= 6.13
|   |   |   |   |   |--- CRIM <= 0.84
|   |   |   |   |   |   |--- AGE <= 78.75
|   |   |   |   |   |   |   |--- RM <= 5.98
|   |   |   |   |   |   |   |   |--- CRIM <= 0.08
|   |   |   |   |   |   |   |   |   |--- PTRATIO <= 17.35
|   |   |   |   |   |   |   |   |   |   |--- value: [20.90]
|   |   |   |   |   |   |   |   |   |--- PTRATIO >  17.35
|   |   |   |   |   |   |   |   |   |   |--- PTRATIO <= 21.10
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |   |   |--- PTRATIO >  21.10
|   |   |   |   |   |   |   |   |   |   |   |--- value: [18.20]
|   |   |   |   |   |   |   |   |--- CRIM >  0.08
|   |   |   |   |   |   |   |   |   |--- DIS <= 3.32
|   |   |   |   |   |   |   |   |   |   |--- value: [22.60]
|   |   |   |   |   |   |   |   |   |--- 

## Knn Regression

In [54]:
# Import libraries
from sklearn.neighbors import KNeighborsRegressor

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state = 1)

In [56]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler = scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [62]:
# create knn model
knnr = KNeighborsRegressor(n_neighbors = 3,weights='distance')

# Train the knn model
model = knnr.fit(X_train, y_train)

# Predict and score the model
model.score(X_test, y_test)

0.8430429455514197

In [63]:
y_pred = model.predict(X_test)
y_pred

array([26.3838981 , 22.51858453, 21.15426247, 20.7960295 , 21.08862864,
       18.99620941, 28.76007987, 17.87967438, 22.25380281, 23.48921229,
       24.20845474, 30.23868052, 20.02490326, 22.42657653, 20.17656719,
       29.41667811, 12.37804993, 34.60201561, 28.93549826, 13.42957158,
       20.48035053, 15.54965851, 21.62568971, 22.40205537, 28.53039376,
        8.48265153, 14.04161027, 17.97670443, 34.33850149, 12.03191934,
       22.1343294 , 18.73320893, 48.11547548, 16.64700051, 20.47733884,
       21.08151958, 15.21839727, 31.45232572, 10.59689937, 20.95961495,
       27.35259258, 21.76684892, 31.16419113, 16.87261106, 17.20476675,
       11.13043986, 42.65069227, 14.35377243, 21.19674157, 13.96481241,
       22.52187738, 21.77475051, 27.15734109, 20.03909167, 11.55934032,
       19.59734776, 11.5023407 , 23.04521717, 18.24189452, 33.57253503,
       14.25719032, 24.56980532, 13.63689412, 15.50920858, 21.94121861,
       38.41202225, 33.88157305, 23.93099802, 25.66669688, 21.45

In [61]:
np.array(y_test)

array([28.2, 23.9, 16.6, 22. , 20.8, 23. , 27.9, 14.5, 21.5, 22.6, 23.7,
       31.2, 19.3, 19.4, 19.4, 27.9, 13.9, 50. , 24.1, 14.6, 16.2, 15.6,
       23.8, 25. , 23.5,  8.3, 13.5, 17.5, 43.1, 11.5, 24.1, 18.5, 50. ,
       12.6, 19.8, 24.5, 14.9, 36.2, 11.9, 19.1, 22.6, 20.7, 30.1, 13.3,
       14.6,  8.4, 50. , 12.7, 25. , 18.6, 29.8, 22.2, 28.7, 23.8,  8.1,
       22.2,  6.3, 22.1, 17.5, 48.3, 16.7, 26.6,  8.5, 14.5, 23.7, 37.2,
       41.7, 16.5, 21.7, 22.7, 23. , 10.5, 21.9, 21. , 20.4, 21.8, 50. ,
       22. , 23.3, 37.3, 18. , 19.2, 34.9, 13.4, 22.9, 22.5, 13. , 24.6,
       18.3, 18.1, 23.9, 50. , 13.6, 22.9, 10.9, 18.9, 22.4, 22.9, 44.8,
       21.7, 10.2, 15.4, 25.3, 23.3,  7.2, 21.2, 11.7, 27. , 29.6, 26.5,
       43.5, 23.6, 11. , 33.4, 36. , 36.4, 19. , 20.2, 34.9, 50. , 19.3,
       14.9, 26.6, 19.9, 24.8, 21.2, 23.9])

## MAE

In [64]:
from sklearn.metrics import mean_absolute_error

mean_absolute_error(y_test, y_pred)

2.899407032923593

In [ ]:
abs(y_test-y_pred).mean()

2.899407032923593

## MSE

In [65]:
from sklearn.metrics import mean_squared_error

display(mean_squared_error(y_test, y_pred))
display(np.sqrt(mean_squared_error(y_test, y_pred)))

15.547926227670997

3.9430858762739365

In [ ]:
np.sqrt(((y_test-y_pred)**2).mean())

## R^2

In [66]:
from sklearn.metrics import r2_score

r2_score(y_test, y_pred)

0.8430429455514197